development:
  adapter: postgresql
  encoding: unicode
  database: vinco_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: vinco_test
  pool: 5
  username: postgres
  password: password
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: vinco_production
  pool: 5
  username: postgres
  password: password
  host: localhost
