# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6056890df91932f3fd502469a6923e18ec6ea343673b04183e3be0c1e1573b1fc2d2aaf408e127d7762ffbb55392350202aef2bf0f6679ea6aa02096a07d487

test:
  secret_key_base: baab0b4f566bece23c4209a3386042d5d2fe3ccfc7c4b7f8195e0b60269f21fcd0ed75f7fd403e95502584c9f9e2d865ee37e2c78910484e78acccecd4106536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
